PLATFORM := $(shell python -c "import os; print(os.name)")
# ifeq (${PLATFORM}, "")
# PLATFORM = $(shell python3 -c "import os; print(os.name)") # this is not assigned.
# endif

main:
	echo ${PLATFORM}