# put device model info here.
# put info into yaml template, which is autogenerated. (suffix: ".tmp") must be renamed and configured to generate this code.

import hydra
from omegaconf import DictConfig, OmegaConf

@hydra.main(version_base=None, 
            config_path=".", 
            # config_path="conf", 
            config_name="config")
def my_app(cfg : DictConfig) -> None:
    print(OmegaConf.to_yaml(cfg))

if __name__ == "__main__":
    my_app()