# put device model info here.
# put info into yaml template, which is autogenerated. (suffix: ".tmp") must be renamed and configured to generate this code.

import rich
import hydra
from omegaconf import DictConfig, OmegaConf

@hydra.main(version_base=None, 
            config_path=".", 
            # config_path="conf", 
            config_name="test_config")
def my_app(cfg : DictConfig) -> None:
    mconfig = OmegaConf.to_yaml(cfg)
    rich.print(mconfig)

if __name__ == "__main__":
    my_app()