FROM microgrid_docplex:latest
ARG BASH=/bin/bash
ARG MICROGRID_DIR=./jubilant-adventure2/microgrid_base

WORKDIR /root

COPY ${MICROGRID_DIR}/init_solver.sh .
RUN ${BASH} init_solver.sh

COPY ${MICROGRID_DIR}/requirements_docplex.txt .
COPY ${MICROGRID_DIR}/init_update_conda_docplex.sh .
RUN ${BASH} init_update_conda_docplex.sh

COPY ${MICROGRID_DIR}/requirements_docker_launch.txt .
COPY ${MICROGRID_DIR}/requirements.txt .
COPY ${MICROGRID_DIR}/init_update_conda_cplex.sh .
RUN ${BASH} init_update_conda_cplex.sh

# finally we run this.
COPY ${MICROGRID_DIR}/init_apt_environ.sh .
RUN ${BASH} init_apt_environ.sh

# we copy files to our workspace
# COPY ${MICROGRID_DIR}${ADDITIONAL_SUFFIX} /root/microgrid_server

# to export it, use it as --build-arg, you must write the below line:
ARG ADDITIONAL_SUFFIX_ARGS

RUN mkdir -p /root/microgrid/server/logs
# ENV ADDITIONAL_SUFFIX $ADDITIONAL_SUFFIX_ARGS
COPY ${MICROGRID_DIR}${ADDITIONAL_SUFFIX_ARGS} /root/microgrid
# RUN echo ${ADDITIONAL_SUFFIX_ARGS}